# Generated by Django 5.0.1 on 2024-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0002_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='mateustum', max_length=10),
            preserve_default=False,
        ),
    ]
